repos:
  - repo: https://github.com/python-poetry/poetry
    rev: 1.7.0
    hooks:
      - id: poetry-check
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=2000']
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [ yagsvc, tests ]
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        args: [ yagsvc, tests ]
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        name: flake8
        args: [ --config, lint/.flake8 ]
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        args: [ --config=lint/.gitlint, --msg-filename ]
  - repo: https://github.com/pycqa/pylint
    rev: v3.0.3
    hooks:
      - id: pylint
        args:
          [
            --rcfile=lint/pylintrc,
            --output-format=colorized,
          ]
        files: yagsvc/
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: [
          marshmallow_dataclass,
          types-python-dateutil,
          types-PyYAML,
          types-requests
        ]
        exclude: tests/
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.6
    hooks:
      - id: bandit
        args: [
            --exclude, tests
        ]
